# Generated by Django 3.2.8 on 2021-10-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField(default=0)),
                ('like_created', models.DateField(auto_now_add=True, verbose_name='%Y-%m-%d')),
                ('like_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to=settings.AUTH_USER_MODEL)),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='publish.report')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.SmallIntegerField(default=0)),
                ('dislike_created', models.DateField(auto_now_add=True, verbose_name='%Y-%m-%d')),
                ('dislike_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_author', to=settings.AUTH_USER_MODEL)),
                ('dislike_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_post', to='publish.report')),
            ],
            options={
                'verbose_name': 'Дизлайк',
                'verbose_name_plural': 'Дизлайки',
            },
        ),
    ]
