# Generated by Django 3.2.8 on 2021-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
